### ISSUE TITLE
I was going to do something like this.

### ISSUE THREAD

**Issue by foxcqrn** [EmeraldFreedom/Freedom#1]
Could I help?

**Comment by foxcqrn** [comment]
@DUFCLiam

**Comment by DUFCLiam** [comment]
Yes you may!

**Comment by foxcqrn** [comment]
Alright thanks.

**Comment by foxcqrn** [comment]
@DUFCLiam FreedomBot has been moved to [MCPluginDev](https://github.com/MCPluginDev/FreedomBot). I need you to accept the request to join the group. Click [here](https://github.com/MCPluginDev) to accept the invite.
